# Generated by Django 2.2.12 on 2021-01-19 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=30, verbose_name='店长姓名')),
                ('mgender', models.BooleanField(null=True, verbose_name='性别')),
                ('mpnum', models.CharField(max_length=11, verbose_name='手机号码')),
                ('mpasswd', models.CharField(max_length=256, verbose_name='密码')),
                ('midnum', models.CharField(max_length=18, verbose_name='身份证号码')),
                ('memail', models.CharField(max_length=20, verbose_name='邮箱')),
                ('misapacity', models.BooleanField(default=1, verbose_name='是否活跃')),
                ('mcreatedtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('mjoinfunds', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='加盟资金')),
                ('mlitime', models.DateTimeField(default='2025-1-1 0:0:0', verbose_name='加盟过期时间')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=50, verbose_name='酒店名称')),
                ('hphum', models.CharField(default='0000', max_length=11, verbose_name='酒店电话')),
                ('hlocation', models.CharField(max_length=128, null=True, verbose_name='酒店地址')),
                ('hmanager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Manager')),
            ],
        ),
    ]
