# Generated by Django 2.2.12 on 2021-01-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isNull', models.BooleanField(default=0, verbose_name='是否入住')),
                ('rtype', models.CharField(default='标准间', max_length=100, verbose_name='房型')),
                ('rprice', models.DecimalField(decimal_places=2, max_digits='7', verbose_name='价格')),
                ('rpeople', models.SmallIntegerField(default=1, max_length=2, verbose_name='入住人数')),
            ],
        ),
    ]
