# Generated by Django 2.2.12 on 2021-01-19 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtype', models.CharField(default='标准间', max_length=100, verbose_name='房型')),
                ('rprice', models.DecimalField(decimal_places=2, max_digits='7', verbose_name='价格')),
                ('rpeople', models.SmallIntegerField(default=1, verbose_name='入住人数')),
                ('rimage', models.ImageField(default='', upload_to='roomImage', verbose_name='房间图片')),
                ('rhotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='RoomStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stime', models.DateField(verbose_name='预定时间')),
                ('rnull', models.BooleanField(default=1, verbose_name='是否为空')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Room')),
            ],
        ),
    ]
