# Generated by Django 2.2.12 on 2021-01-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='rpeople',
            field=models.SmallIntegerField(default=1, verbose_name='入住人数'),
        ),
    ]
